### ISSUE TITLE
Failed to apply dev bundles

### ISSUE THREAD

**Issue by ThrowerWay** [PaperMC/paperweight#217] opened 2023-10-10 02:20 UTC
plugins {
    java
    `maven-publish`
    id("io.papermc.paperweight.userdev") version "1.5.9-SNAPSHOT"
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }
    maven {
        url = uri("https://repo.opencollab.dev/maven-snapshots/")
    }
    maven {
        url = uri("https://jitpack.io/")
    }
}
...

Could not determine the dependencies of task ':compileJava'.
> Could not resolve all dependencies for configuration ':compileClasspath'.
   > Failed to apply dev bundle patches. See the log file at 'C:\Users\Jape\Documents\TestProject\.gradle\caches\paperweight\setupCache\patchedSourcesJar.log' for more details. Usually, the issue is with the dev bundle itself, and not the userdev project.

patchedSourcesJar.log:
...
Patching: net/minecraft/world/entity/monster/piglin/Piglin.java
 Hunk 0: EXACT: @@ -5,14 +5,6 @@
 Hunk 1: EXACT: @@ -54,13 +46,33 @@
 Hunk 2: EXACT: @@ -73,7 +85,11 @@
 Hunk 3: EXACT: @@ -92,6 +108,14 @@
 Hunk 4: FAILURE: @@ -100,6 +124,10 @@
 ...
 Patch Summary:
 Un-changed files: 2874
 Changed files:    778
 Missing files:    0

 Failed matches:   1
 Exact matches:    4966
 Access matches:   0
 Offset matches:   0
 Fuzzy matches:    0
Overall Quality   99.98%

**Comment by MiniDigger** [comment] 2023-10-10 07:05
duplicate of #215 
make sure you use the latest dev bundle, the userdev version doesnt matter

**Closed by MiniDigger** 2023-10-10 07:05 UTC

**Comment by electronicboy** [comment] 2023-10-10 11:34
run with `--refresh-dependencies` you have an old dev bundle

**Comment by electronicboy** [comment] 2023-10-10 11:35
you would need to do it in a terminal or add it to a run task

**Comment by electronicboy** [comment] 2023-10-10 11:37
it's an argument you pass to gradle when running build

**Comment by MiniDigger** [comment] 2023-10-10 13:40
> if you need help with that please join our discord #build-tooling-help
